/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  //ContinueSwitch page :
  static readonly IMAGE_COUNT:number = 85;
  static readonly IMG_ANIMATOR_OVER_DURATION:number = 1000;
  static readonly IMG_ANIMATOR_NORMAL_DURATION:number = 30;
  static readonly SWITCH_STATUS_OPEN:string = '1';
  static readonly SWITCH_STATUS_CLOSE:string = '0';
  static readonly GENERAL_PHONE_GAP_LENGTH:number = 16;
  static readonly PC_PAD_GAP_LENGTH:number = 24;
  static readonly PC_LIST_HEIGHT:number = 48;
  static readonly PHONE_LIST_HEIGHT:number = 56;
  static readonly TEXT_LIST_ALIGN_DISTANCE:number = 12;
  static readonly PC_BORDER_RADIUS:number = 16;
  static readonly NON_PC_BORDER_RADIUS:number = 20;
  static readonly CONTINUE_DESC_TEXT_MARGIN_BOTTOM:number = 32;
  static readonly CONTINUE_PRIVACY_TEXT_MARGIN_TOP:number = 8;
  static readonly CONTINUE_SWITCH_WIDTH:number = 36;
  static readonly CONTINUE_SWITCH_HEIGHT:number = 20;
}